"""empty message

Revision ID: 4f4d6110d156
Revises: cae798d54e63
Create Date: 2022-12-07 14:56:06.249634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4d6110d156'
down_revision = 'cae798d54e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('destination', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'destination')
    # ### end Alembic commands ###
