"""empty message

Revision ID: 655c08a49085
Revises: 351206ba4a04
Create Date: 2022-11-28 21:54:32.636974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655c08a49085'
down_revision = '351206ba4a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('user', 'name')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
