"""empty message

Revision ID: 744ef7bc83d9
Revises: 7a1b27e1fb76
Create Date: 2022-12-05 21:40:42.209647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744ef7bc83d9'
down_revision = '7a1b27e1fb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('destination', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'destination')
    # ### end Alembic commands ###
