"""empty message

Revision ID: 9863d840e254
Revises: 50a94fb24b8b
Create Date: 2022-11-30 21:10:55.755499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9863d840e254'
down_revision = '50a94fb24b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image', sa.LargeBinary(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image')
    # ### end Alembic commands ###
